name: Publish crate
description: Publish crate on crates.io and create release on github
inputs:
  cargo-registry-token:
    description: 'API token for crates.io'
    required: true
  github-token:
    description: 'Github API token'
    required: true

runs:
  using: composite
  steps:
    - name: Read changelog
      id: changelog-reader
      uses: mindsers/changelog-reader-action@v2
      with:
        # validation_depth: 10
        version: ${{ (github.ref_type == 'tag' && !contains(github.ref_name, '-') && github.ref_name) || 'Unreleased' }}
        path: ./CHANGELOG.md

    - name: Download artifacts
      id: download-artifacts
      uses: actions/download-artifact@v4
      with:
        path:
          ${{ runner.temp }}/artifacts

    - name: Log into crates.io
      if: >
        github.event_name == 'push' && (
          github.ref == format('refs/heads/{0}', github.event.repository.default_branch) ||
          startsWith(github.ref, 'refs/tags/v')
        )
      run: cargo login ${{ inputs.cargo-registry-token }}
      shell: bash

    - run: gh release delete --yes Unreleased || exit 0
      if: >
        github.event_name == 'push' &&
          github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}

    - name: Create GitHub release
      if: >
        github.event_name == 'push' && (
          github.ref == format('refs/heads/{0}', github.event.repository.default_branch) ||
          startsWith(github.ref, 'refs/tags/v')
        )
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ (github.ref_type == 'tag' && github.ref_name) || 'Unreleased' }}
        body: ${{ steps.changelog-reader.outputs.changes }}
        prerelease: ${{ startsWith(github.ref, 'refs/tags/v') && contains(github.ref_name, '-') }}
        draft: ${{ !startsWith(github.ref, 'refs/tags/v') && steps.changelog-reader.outputs.status == 'unreleased' }}
        files: |
          ${{ steps.download-artifacts.outputs.download-path }}/cross-*/*

    - name: Publish crate
      run: cargo publish ${{ !startsWith(github.ref, 'refs/tags/v') && '--dry-run' || '' }}
      shell: bash
