FROM ghcr.io/cross-rs/base:main-ubuntu
ARG DEBIAN_FRONTEND=noninteractive

COPY netbsd.sh /
RUN /netbsd.sh

ENV CARGO_TARGET_X86_64_UNKNOWN_NETBSD_LINKER=x86_64-unknown-netbsd-gcc \
    CC_x86_64_unknown_netbsd=x86_64-unknown-netbsd-gcc \
    CXX_x86_64_unknown_netbsd=x86_64-unknown-netbsd-g++ \
    BINDGEN_EXTRA_CLANG_ARGS_x86_64_unknown_netbsd="--sysroot=/usr/local/x86_64-unknown-netbsd"
