FROM ubuntu:20.04
ARG DEBIAN_FRONTEND=noninteractive

COPY common.sh lib.sh /
RUN /common.sh

COPY cmake.sh /
RUN /cmake.sh

COPY xargo.sh /
RUN /xargo.sh

RUN echo "export ARCH=x86_64" > /freebsd-arch.sh
COPY freebsd-common.sh /
COPY freebsd.sh /
RUN /freebsd.sh

COPY freebsd-install.sh /
COPY freebsd-extras.sh /
RUN /freebsd-extras.sh

ENV CROSS_TOOLCHAIN_PREFIX=x86_64-unknown-freebsd12-
ENV CROSS_SYSROOT=/usr/local/x86_64-unknown-freebsd12

COPY freebsd-gcc.sh /usr/bin/"$CROSS_TOOLCHAIN_PREFIX"gcc.sh

ENV CARGO_TARGET_X86_64_UNKNOWN_FREEBSD_LINKER="$CROSS_TOOLCHAIN_PREFIX"gcc.sh \
    AR_x86_64_unknown_freebsd="$CROSS_TOOLCHAIN_PREFIX"ar \
    CC_x86_64_unknown_freebsd="$CROSS_TOOLCHAIN_PREFIX"gcc \
    CXX_x86_64_unknown_freebsd="$CROSS_TOOLCHAIN_PREFIX"g++ \
    BINDGEN_EXTRA_CLANG_ARGS_x86_64_unknown_freebsd="--sysroot=$CROSS_SYSROOT" \
    X86_64_UNKNOWN_FREEBSD_OPENSSL_DIR="$CROSS_SYSROOT"
