FROM ubuntu:20.04 AS cross-base
ENV DEBIAN_FRONTEND=noninteractive

COPY common.sh lib.sh /
RUN /common.sh

COPY cmake.sh /
RUN /cmake.sh

COPY xargo.sh /
RUN /xargo.sh

FROM cross-base AS build

RUN echo "export ARCH=powerpc64le" > /freebsd-arch.sh
COPY freebsd-common.sh /
COPY freebsd.sh /
RUN /freebsd.sh

COPY freebsd-install.sh /
COPY freebsd-extras.sh /
RUN /freebsd-extras.sh

ENV CROSS_TOOLCHAIN_PREFIX=powerpc64le-unknown-freebsd13-
ENV CROSS_SYSROOT=/usr/local/powerpc64le-unknown-freebsd13

COPY freebsd-gcc.sh /usr/bin/"$CROSS_TOOLCHAIN_PREFIX"gcc.sh
COPY toolchain.cmake /opt/toolchain.cmake

COPY freebsd-fetch-best-mirror.sh /
COPY freebsd-setup-packagesite.sh /
COPY freebsd-install-package.sh /

ENV CARGO_TARGET_POWERPC64LE_UNKNOWN_FREEBSD_LINKER="$CROSS_TOOLCHAIN_PREFIX"gcc.sh \
    AR_powerpc64le_unknown_freebsd="$CROSS_TOOLCHAIN_PREFIX"ar \
    CC_powerpc64le_unknown_freebsd="$CROSS_TOOLCHAIN_PREFIX"gcc \
    CXX_powerpc64le_unknown_freebsd="$CROSS_TOOLCHAIN_PREFIX"g++ \
    CMAKE_TOOLCHAIN_FILE_powerpc64le_unknown_freebsd=/opt/toolchain.cmake \
    BINDGEN_EXTRA_CLANG_ARGS_powerpc64le_unknown_freebsd="--sysroot=$CROSS_SYSROOT" \
    POWERPC64LE_UNKNOWN_FREEBSD_OPENSSL_DIR="$CROSS_SYSROOT" \
    PKG_CONFIG_PATH="${CROSS_SYSROOT}/libdata/pkgconfig/:${PKG_CONFIG_PATH}" \
    PKG_CONFIG_ALLOW_CROSS=1 \
    CROSS_CMAKE_SYSTEM_NAME=FreeBSD \
    CROSS_CMAKE_SYSTEM_PROCESSOR=powerpc64le \
    CROSS_CMAKE_CRT=freebsd \
    CROSS_CMAKE_OBJECT_FLAGS="-ffunction-sections -fdata-sections -fPIC"
