FROM ghcr.io/cross-rs/base:main-emscripten
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get update && apt-get install --assume-yes --no-install-recommends \
  libxml2 \
  python

ENV CARGO_TARGET_ASMJS_UNKNOWN_EMSCRIPTEN_RUNNER=node \
  BINDGEN_EXTRA_CLANG_ARGS_asmjs_unknown_emscripten="--sysroot=/emsdk/upstream/emscripten/cache/sysroot"
