FROM ubuntu:20.04
ARG DEBIAN_FRONTEND=noninteractive

COPY common.sh lib.sh /
RUN /common.sh

COPY cmake.sh /
RUN /cmake.sh

COPY xargo.sh /
RUN /xargo.sh

COPY musl.sh /
RUN /musl.sh TARGET=i586-linux-musl

COPY qemu.sh /
RUN /qemu.sh i386

ENV CROSS_TOOLCHAIN_PREFIX=i586-linux-musl-
ENV CROSS_SYSROOT=/usr/local/i586-linux-musl
COPY musl-symlink.sh /
RUN /musl-symlink.sh $CROSS_SYSROOT i386

COPY qemu-runner base-runner.sh /

ENV CARGO_TARGET_I586_UNKNOWN_LINUX_MUSL_LINKER="$CROSS_TOOLCHAIN_PREFIX"gcc \
    CARGO_TARGET_I586_UNKNOWN_LINUX_MUSL_RUNNER="/qemu-runner i586" \
    AR_i586_unknown_linux_musl="$CROSS_TOOLCHAIN_PREFIX"ar \
    CC_i586_unknown_linux_musl="$CROSS_TOOLCHAIN_PREFIX"gcc \
    CXX_i586_unknown_linux_musl="$CROSS_TOOLCHAIN_PREFIX"g++ \
    BINDGEN_EXTRA_CLANG_ARGS_i586_unknown_linux_musl="--sysroot=$CROSS_SYSROOT" \
    QEMU_LD_PREFIX="$CROSS_SYSROOT"
