FROM rust:latest

ENV CROSS_DOCKER_IN_DOCKER=true

RUN wget -O- https://download.docker.com/linux/static/stable/x86_64/docker-20.10.9.tgz | tar -C /usr/bin/ --strip-components=1 -xzf - docker/docker

RUN cargo install cross
