FROM ubuntu:18.04
ARG DEBIAN_FRONTEND=noninteractive

COPY common.sh lib.sh /
RUN /common.sh

# COPY cmake.sh /
# RUN /cmake.sh

COPY xargo.sh /
RUN /xargo.sh

RUN apt-get update && apt-get install -y --no-install-recommends \
    g++-riscv64-linux-gnu \
    libc6-dev-riscv64-cross

COPY qemu.sh /
RUN /qemu.sh riscv64

COPY linux-runner /

ENV CARGO_TARGET_RISCV64GC_UNKNOWN_LINUX_GNU_LINKER=riscv64-linux-gnu-gcc \
    CARGO_TARGET_RISCV64GC_UNKNOWN_LINUX_GNU_RUNNER="/linux-runner riscv64" \
    CC_riscv64gc_unknown_linux_gnu=riscv64-linux-gnu-gcc \
    CXX_riscv64gc_unknown_linux_gnu=riscv64-linux-gnu-g++ \
    QEMU_LD_PREFIX=/usr/riscv64-linux-gnu \
    RUST_TEST_THREADS=1
