FROM ubuntu:18.04

COPY common.sh lib.sh /
RUN /common.sh

COPY cmake.sh /
RUN /cmake.sh

COPY xargo.sh /
RUN /xargo.sh

COPY qemu.sh /
RUN /qemu.sh mips64

COPY musl.sh /
RUN /musl.sh \
    TARGET=mips64-linux-muslsf \
    "COMMON_CONFIG += -with-arch=mips64r2"

# This allows qemu run dynamic linked binaries
RUN ln -sf \
    /usr/local/mips64-linux-muslsf/lib/libc.so \
    /usr/local/mips64-linux-muslsf/lib/ld-musl-mips64-sf.so.1
ENV QEMU_LD_PREFIX=/usr/local/mips64-linux-muslsf

ENV CARGO_TARGET_MIPS64_UNKNOWN_LINUX_MUSLABI64_LINKER=mips64-linux-muslsf-gcc \
    CARGO_TARGET_MIPS64_UNKNOWN_LINUX_MUSLABI64_RUNNER=qemu-mips64 \
    CC_mips64_unknown_linux_muslabi64=mips64-linux-muslsf-gcc \
    CXX_mips64_unknown_linux_muslabi64=mips64-linux-muslsf-g++ \
    RUST_TEST_THREADS=1
