FROM ubuntu:20.04 as cross-base
ENV DEBIAN_FRONTEND=noninteractive

COPY common.sh lib.sh /
RUN /common.sh

COPY cmake.sh /
RUN /cmake.sh

COPY xargo.sh /
RUN /xargo.sh

FROM cross-base as build

COPY qemu.sh /
RUN /qemu.sh arm

ARG ANDROID_NDK=r25b
ARG ANDROID_SDK=28
ARG ANDROID_VERSION=9.0.0_r1
ARG ANDROID_SYSTEM_NONE=0
ARG ANDROID_SYSTEM_COMPLETE=0
ARG PYTHON_TMPDIR=/tmp/android

COPY validate-android-args.sh /
RUN /validate-android-args.sh arm

COPY android-ndk.sh /
RUN /android-ndk.sh arm
ENV PATH=$PATH:/android-ndk/bin

COPY android-system.sh /
RUN mkdir -p $PYTHON_TMPDIR
COPY android $PYTHON_TMPDIR
RUN /android-system.sh arm

ENV CROSS_TOOLCHAIN_PREFIX=arm-linux-androideabi-
ENV CROSS_SYSROOT=/android-ndk/sysroot
ENV CROSS_ANDROID_SDK=$ANDROID_SDK
COPY android-symlink.sh /
RUN /android-symlink.sh arm arm-linux-androideabi

COPY android-runner /
COPY android.cmake /opt/toolchain.cmake

# Libz is distributed in the android ndk, but for some unknown reason it is not
# found in the build process of some crates, so we explicit set the DEP_Z_ROOT
ENV CROSS_TARGET_RUNNER="/android-runner arm"
ENV CARGO_TARGET_ARMV7_LINUX_ANDROIDEABI_LINKER="$CROSS_TOOLCHAIN_PREFIX"gcc \
    CARGO_TARGET_ARMV7_LINUX_ANDROIDEABI_RUNNER="$CROSS_TARGET_RUNNER" \
    AR_armv7_linux_androideabi="$CROSS_TOOLCHAIN_PREFIX"ar \
    AS_armv7_linux_androideabi="$CROSS_TOOLCHAIN_PREFIX"as \
    CC_armv7_linux_androideabi="$CROSS_TOOLCHAIN_PREFIX"gcc \
    CXX_armv7_linux_androideabi="$CROSS_TOOLCHAIN_PREFIX"g++ \
    LD_armv7_linux_androideabi="$CROSS_TOOLCHAIN_PREFIX"ld \
    NM_armv7_linux_androideabi="$CROSS_TOOLCHAIN_PREFIX"nm \
    OBJCOPY_armv7_linux_androideabi="$CROSS_TOOLCHAIN_PREFIX"objcopy \
    OBJDUMP_armv7_linux_androideabi="$CROSS_TOOLCHAIN_PREFIX"objdump \
    RANLIB_armv7_linux_androideabi="$CROSS_TOOLCHAIN_PREFIX"ranlib \
    READELF_armv7_linux_androideabi="$CROSS_TOOLCHAIN_PREFIX"readelf \
    SIZE_armv7_linux_androideabi="$CROSS_TOOLCHAIN_PREFIX"size \
    STRINGS_armv7_linux_androideabi="$CROSS_TOOLCHAIN_PREFIX"strings \
    STRIP_armv7_linux_androideabi="$CROSS_TOOLCHAIN_PREFIX"strip \
    CMAKE_TOOLCHAIN_FILE_armv7_linux_androideabi=/opt/toolchain.cmake \
    BINDGEN_EXTRA_CLANG_ARGS_armv7_linux_androideabi="--sysroot=$CROSS_SYSROOT" \
    DEP_Z_INCLUDE="$CROSS_SYSROOT/usr/include/" \
    RUST_TEST_THREADS=1 \
    HOME=/tmp/ \
    TMPDIR=/tmp/ \
    ANDROID_DATA=/ \
    ANDROID_DNS_MODE=local \
    ANDROID_ROOT=/system \
    CROSS_CMAKE_SYSTEM_NAME=Android \
    CROSS_CMAKE_SYSTEM_PROCESSOR=armv7-a \
    CROSS_CMAKE_CRT=android \
    CROSS_CMAKE_OBJECT_FLAGS="--target=arm-linux-androideabi -DANDROID -ffunction-sections -fdata-sections -fPIC --target=armv7-linux-androideabi"
