FROM ubuntu:24.04 AS cross-base
ENV DEBIAN_FRONTEND=noninteractive

COPY common.sh lib.sh /
RUN /common.sh

COPY cmake.sh /
RUN /cmake.sh

FROM cross-base AS build

ARG VERBOSE
COPY crosstool-ng.sh /
COPY crosstool-config/aarch64_be-unknown-linux-musl.config /
RUN /crosstool-ng.sh aarch64_be-unknown-linux-musl.config 5

ENV PATH=/x-tools/aarch64_be-unknown-linux-musl/bin/:$PATH

COPY qemu.sh /
RUN /qemu.sh aarch64_be

COPY qemu-runner base-runner.sh /
COPY toolchain.cmake /opt/toolchain.cmake

COPY tidyup.sh /
RUN /tidyup.sh

ENV CROSS_TOOLCHAIN_PREFIX=aarch64_be-unknown-linux-musl-
ENV CROSS_SYSROOT=/x-tools/aarch64_be-unknown-linux-musl/aarch64_be-unknown-linux-musl/sysroot/
ENV CROSS_TARGET_RUNNER="/qemu-runner aarch64_be"
ENV CARGO_TARGET_AARCH64_BE_UNKNOWN_LINUX_GNU_LINKER="$CROSS_TOOLCHAIN_PREFIX"gcc \
    CARGO_TARGET_AARCH64_BE_UNKNOWN_LINUX_GNU_RUNNER="$CROSS_TARGET_RUNNER" \
    AR_aarch64_be_unknown_linux_musl="$CROSS_TOOLCHAIN_PREFIX"ar \
    CC_aarch64_be_unknown_linux_musl="$CROSS_TOOLCHAIN_PREFIX"gcc \
    CXX_aarch64_be_unknown_linux_musl="$CROSS_TOOLCHAIN_PREFIX"g++ \
    CMAKE_TOOLCHAIN_FILE_aarch64_be_unknown_linux_musl=/opt/toolchain.cmake \
    BINDGEN_EXTRA_CLANG_ARGS_aarch64_be_unknown_linux_musl="--sysroot=$CROSS_SYSROOT -idirafter/usr/include" \
    QEMU_LD_PREFIX="$CROSS_SYSROOT" \
    RUST_TEST_THREADS=1 \
    CROSS_CMAKE_SYSTEM_NAME=Linux \
    CROSS_CMAKE_SYSTEM_PROCESSOR=aarch64_be \
    CROSS_CMAKE_CRT=musl \
    CROSS_CMAKE_OBJECT_FLAGS="-ffunction-sections -fdata-sections -fPIC"

RUN sed -e "s#@DEFAULT_QEMU_LD_PREFIX@#$QEMU_LD_PREFIX#g" -i /qemu-runner
