FROM ubuntu:24.04 AS cross-base
ENV DEBIAN_FRONTEND=noninteractive

COPY ubuntu.sources /etc/apt/sources.list.d/
COPY common.sh lib.sh /
RUN /common.sh

COPY cmake.sh /
RUN /cmake.sh

FROM cross-base AS build

COPY qemu.sh /
RUN /qemu.sh arm

ARG VERBOSE
COPY crosstool-ng.sh /
COPY crosstool-config/arm-unknown-linux-musleabi.config /
RUN /crosstool-ng.sh arm-unknown-linux-musleabi.config 5

ENV PATH=/x-tools/arm-unknown-linux-musleabi/bin/:$PATH

COPY tidyup.sh /
RUN /tidyup.sh

FROM scratch AS final
COPY --from=build / /
CMD ["/bin/bash"]
ENV PATH=/x-tools/arm-unknown-linux-musleabi/bin/:$PATH

ENV CROSS_TOOLCHAIN_PREFIX=arm-unknown-linux-musleabi-
ENV CROSS_SYSROOT=/x-tools/arm-unknown-linux-musleabi/arm-unknown-linux-musleabi/sysroot/

COPY qemu-runner base-runner.sh /
COPY toolchain.cmake /opt/toolchain.cmake

ENV CROSS_TARGET_RUNNER="/qemu-runner arm"
ENV CARGO_TARGET_ARM_UNKNOWN_LINUX_MUSLEABI_LINKER="$CROSS_TOOLCHAIN_PREFIX"gcc \
    CARGO_TARGET_ARM_UNKNOWN_LINUX_MUSLEABI_RUNNER="$CROSS_TARGET_RUNNER" \
    AR_arm_unknown_linux_musleabi="$CROSS_TOOLCHAIN_PREFIX"ar \
    CC_arm_unknown_linux_musleabi="$CROSS_TOOLCHAIN_PREFIX"gcc \
    CXX_arm_unknown_linux_musleabi="$CROSS_TOOLCHAIN_PREFIX"g++ \
    CMAKE_TOOLCHAIN_FILE_arm_unknown_linux_musleabi=/opt/toolchain.cmake \
    BINDGEN_EXTRA_CLANG_ARGS_arm_unknown_linux_musleabi="--sysroot=$CROSS_SYSROOT" \
    QEMU_LD_PREFIX="$CROSS_SYSROOT" \
    RUST_TEST_THREADS=1 \
    CROSS_CMAKE_SYSTEM_NAME=Linux \
    CROSS_CMAKE_SYSTEM_PROCESSOR=arm \
    CROSS_CMAKE_CRT=musl \
    CROSS_CMAKE_OBJECT_FLAGS="-ffunction-sections -fdata-sections -fPIC -march=armv6 -marm -mfloat-abi=soft"

RUN sed -e "s#@DEFAULT_QEMU_LD_PREFIX@#$QEMU_LD_PREFIX#g" -i /qemu-runner
