FROM ubuntu:20.04
ARG DEBIAN_FRONTEND=noninteractive

COPY common.sh lib.sh /
RUN /common.sh

COPY cmake.sh /
RUN /cmake.sh

COPY xargo.sh /
RUN /xargo.sh

COPY netbsd.sh /
RUN /netbsd.sh

ENV CROSS_TOOLCHAIN_PREFIX=x86_64-unknown-netbsd-
ENV CROSS_SYSROOT=/usr/local/x86_64-unknown-netbsd
ENV CARGO_TARGET_X86_64_UNKNOWN_NETBSD_LINKER="$CROSS_TOOLCHAIN_PREFIX"gcc \
    AR_x86_64_unknown_netbsd="$CROSS_TOOLCHAIN_PREFIX"ar \
    CC_x86_64_unknown_netbsd="$CROSS_TOOLCHAIN_PREFIX"gcc \
    CXX_x86_64_unknown_netbsd="$CROSS_TOOLCHAIN_PREFIX"g++ \
    BINDGEN_EXTRA_CLANG_ARGS_x86_64_unknown_netbsd="--sysroot=$CROSS_SYSROOT"
