FROM ubuntu:16.04

COPY common.sh /
RUN /common.sh

COPY xargo.sh /
RUN /xargo.sh

COPY cmake.sh /
RUN apt-get purge --auto-remove -y cmake && \
    /cmake.sh

RUN mkdir /usr/arm-linux-gnueabihf && \
    apt-get install -y --no-install-recommends curl xz-utils && \
    cd /usr/arm-linux-gnueabihf && \
    curl -L https://releases.linaro.org/components/toolchain/binaries/latest-7/arm-linux-gnueabihf/gcc-linaro-7.4.1-2019.02-x86_64_arm-linux-gnueabihf.tar.xz | \
    tar --strip-components 1 -xJ && \
    apt-get purge --auto-remove -y curl xz-utils

ENV PATH /usr/arm-linux-gnueabihf/bin:$PATH

COPY qemu.sh /

RUN /qemu.sh arm

RUN apt-get install -y --no-install-recommends \
    libc6-dev-armhf-cross

ENV CARGO_TARGET_ARM_UNKNOWN_LINUX_GNUEABIHF_LINKER=arm-linux-gnueabihf-gcc \
    CARGO_TARGET_ARM_UNKNOWN_LINUX_GNUEABIHF_RUNNER=qemu-arm \
    CC_arm_unknown_linux_gnueabihf=arm-linux-gnueabihf-gcc \
    CXX_arm_unknown_linux_gnueabihf=arm-linux-gnueabihf-g++ \
    QEMU_LD_PREFIX=/usr/arm-linux-gnueabihf \
    LD_LIBRARY_PATH=/usr/arm-linux-gnueabihf/lib:/usr/arm-linux-gnueabihf/arm-linux-gnueabihf/lib \
    RUST_TEST_THREADS=1
