FROM ubuntu:16.04

COPY common.sh /
RUN /common.sh

RUN apt-get install -y --no-install-recommends python

COPY emscripten.sh /
RUN /emscripten.sh

COPY emscripten-entry.sh /
ENTRYPOINT ["/emscripten-entry.sh"]

ENV CARGO_TARGET_ASMJS_UNKNOWN_EMSCRIPTEN_RUNNER=node
