FROM ubuntu:20.04
ARG DEBIAN_FRONTEND=noninteractive

COPY lib.sh /
COPY linux-image.sh /
RUN /linux-image.sh x86_64

FROM ghcr.io/cross-rs/base:main-centos

COPY qemu.sh /
RUN /qemu.sh x86_64 softmmu

COPY dropbear.sh /
RUN /dropbear.sh

COPY --from=0 /qemu /qemu

COPY linux-runner base-runner.sh /

ENV CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUNNER="/linux-runner x86_64"
