FROM ubuntu:16.04

COPY common.sh lib.sh /
RUN /common.sh

COPY cmake.sh /
RUN /cmake.sh

COPY xargo.sh /
RUN /xargo.sh

COPY qemu.sh /
RUN apt-get install --assume-yes --no-install-recommends \
    gcc-arm-none-eabi \
    libnewlib-arm-none-eabi && \
    /qemu.sh arm

ENV QEMU_CPU=cortex-m4 \
    CARGO_TARGET_THUMBV7EM_NONE_EABI_RUNNER=qemu-arm
