FROM ubuntu:24.04 AS cross-base
ENV DEBIAN_FRONTEND=noninteractive

COPY ubuntu.sources /etc/apt/sources.list.d/
COPY common.sh lib.sh /
RUN /common.sh

COPY cmake.sh /
RUN /cmake.sh

FROM cross-base AS build

ARG VERBOSE
COPY crosstool-ng.sh /
COPY crosstool-config/x86_64-unknown-linux-musl.config /
RUN /crosstool-ng.sh x86_64-unknown-linux-musl.config 5

ENV PATH=/x-tools/x86_64-unknown-linux-musl/bin/:$PATH

COPY qemu.sh /
RUN /qemu.sh x86_64

COPY tidyup.sh /
RUN /tidyup.sh

FROM scratch AS final
COPY --from=build / /
CMD ["/bin/bash"]
ENV PATH=/x-tools/x86_64-unknown-linux-musl/bin/:$PATH

COPY qemu-runner base-runner.sh /
COPY toolchain.cmake /opt/toolchain.cmake

ENV CROSS_TOOLCHAIN_PREFIX=x86_64-unknown-linux-musl-
ENV CROSS_SYSROOT=/x-tools/x86_64-unknown-linux-musl/x86_64-unknown-linux-musl/sysroot/

# Allow dynamically-linked musl binaries to run natively.
RUN ln -sf "$CROSS_SYSROOT/lib/ld-musl-x86_64.so.1" /lib/ld-musl-x86_64.so.1 \
    && echo "$CROSS_SYSROOT/lib" > /etc/ld-musl-x86_64.path

ENV CROSS_TARGET_RUNNER="/qemu-runner x86_64"
ENV CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_LINKER="$CROSS_TOOLCHAIN_PREFIX"gcc \
    CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_RUNNER="$CROSS_TARGET_RUNNER" \
    AR_x86_64_unknown_linux_musl="$CROSS_TOOLCHAIN_PREFIX"ar \
    CC_x86_64_unknown_linux_musl="$CROSS_TOOLCHAIN_PREFIX"gcc \
    CXX_x86_64_unknown_linux_musl="$CROSS_TOOLCHAIN_PREFIX"g++ \
    CMAKE_TOOLCHAIN_FILE_x86_64_unknown_linux_musl=/opt/toolchain.cmake \
    BINDGEN_EXTRA_CLANG_ARGS_x86_64_unknown_linux_musl="--sysroot=$CROSS_SYSROOT" \
    QEMU_LD_PREFIX="$CROSS_SYSROOT" \
    CROSS_CMAKE_SYSTEM_NAME=Linux \
    CROSS_CMAKE_SYSTEM_PROCESSOR=x86_64 \
    CROSS_CMAKE_CRT=musl \
    CROSS_CMAKE_OBJECT_FLAGS="-ffunction-sections -fdata-sections -fPIC -m64"

RUN sed -e "s#@DEFAULT_QEMU_LD_PREFIX@#$QEMU_LD_PREFIX#g" -i /qemu-runner
