FROM ubuntu:18.04
ARG DEBIAN_FRONTEND=noninteractive

COPY common.sh lib.sh /
RUN /common.sh

COPY cmake.sh /
RUN /cmake.sh

COPY xargo.sh /
RUN /xargo.sh

COPY qemu.sh /
RUN /qemu.sh mips

COPY musl.sh /
RUN /musl.sh \
    TARGET=mips-linux-muslsf \
    "COMMON_CONFIG += -with-arch=mips32r2"

# Allows qemu run dynamic linked binaries
RUN ln -sf \
    /usr/local/mips-linux-muslsf/lib/libc.so \
    /usr/local/mips-linux-muslsf/lib/ld-musl-mips-sf.so.1
ENV QEMU_LD_PREFIX=/usr/local/mips-linux-muslsf

ENV CARGO_TARGET_MIPS_UNKNOWN_LINUX_MUSL_LINKER=mips-linux-muslsf-gcc \
    CARGO_TARGET_MIPS_UNKNOWN_LINUX_MUSL_RUNNER=qemu-mips \
    CC_mips_unknown_linux_musl=mips-linux-muslsf-gcc \
    CXX_mips_unknown_linux_musl=mips-linux-muslsf-g++ \
    RUST_TEST_THREADS=1 \
    QEMU_LD_PREFIX=/usr/local/mips-linux-muslsf
