FROM ubuntu:20.04
ARG DEBIAN_FRONTEND=noninteractive

COPY common.sh lib.sh /
RUN /common.sh

COPY cmake.sh /
RUN /cmake.sh

COPY xargo.sh /
RUN /xargo.sh

COPY qemu.sh /
RUN apt-get update && apt-get install --assume-yes --no-install-recommends \
    gcc-arm-none-eabi \
    libnewlib-arm-none-eabi && \
    /qemu.sh arm

ENV QEMU_CPU=cortex-m4 \
    AR_thumbv7em_none_eabihf=arm-none-eabi-ar \
    CC_thumbv7em_none_eabihf=arm-none-eabi-gcc \
    CXX_thumbv7em_none_eabihf=arm-none-eabi-g++ \
    CARGO_TARGET_THUMBV7EM_NONE_EABIHF_RUNNER=qemu-arm
