FROM ubuntu:18.04

COPY common.sh lib.sh /
RUN /common.sh

COPY cmake.sh /
RUN /cmake.sh

COPY xargo.sh /
RUN /xargo.sh

COPY qemu.sh /
RUN /qemu.sh mipsel

COPY musl.sh /
RUN /musl.sh \
    TARGET=mipsel-linux-muslsf \
    "COMMON_CONFIG += -with-arch=mips32"

# This allows qemu run dynamic linked binaries
RUN ln -sf \
    /usr/local/mipsel-linux-muslsf/lib/libc.so \
    /usr/local/mipsel-linux-muslsf/lib/ld-musl-mipsel-sf.so.1
ENV QEMU_LD_PREFIX=/usr/local/mipsel-linux-muslsf

ENV CARGO_TARGET_MIPSEL_UNKNOWN_LINUX_MUSL_LINKER=mipsel-linux-muslsf-gcc \
    CARGO_TARGET_MIPSEL_UNKNOWN_LINUX_MUSL_RUNNER=qemu-mipsel \
    CC_mipsel_unknown_linux_musl=mipsel-linux-muslsf-gcc \
    CXX_mipsel_unknown_linux_musl=mipsel-linux-muslsf-g++ \
    RUST_TEST_THREADS=1
