FROM ubuntu:18.04
ARG DEBIAN_FRONTEND=noninteractive

COPY common.sh lib.sh /
RUN /common.sh

COPY cmake.sh /
RUN /cmake.sh

COPY xargo.sh /
RUN /xargo.sh

COPY musl.sh /
RUN /musl.sh TARGET=i586-linux-musl

ENV CARGO_TARGET_I586_UNKNOWN_LINUX_MUSL_LINKER=i586-linux-musl-gcc \
    CC_i586_unknown_linux_musl=i586-linux-musl-gcc \
    CXX_i586_unknown_linux_musl=i586-linux-musl-g++
