FROM ubuntu:18.04

COPY common.sh lib.sh /
RUN /common.sh

COPY cmake.sh /
RUN /cmake.sh

COPY xargo.sh /
RUN /xargo.sh

COPY musl.sh /
RUN /musl.sh TARGET=i686-linux-musl

COPY qemu.sh /
RUN /qemu.sh i386 softmmu

COPY dropbear.sh /
RUN /dropbear.sh

COPY linux-image.sh /
RUN /linux-image.sh i686

COPY linux-runner /

ENV CARGO_TARGET_I686_UNKNOWN_LINUX_MUSL_LINKER=i686-linux-musl-gcc \
    CARGO_TARGET_I686_UNKNOWN_LINUX_MUSL_RUNNER="/linux-runner i686" \
    CC_i686_unknown_linux_musl=i686-linux-musl-gcc \
    CXX_i686_unknown_linux_musl=i686-linux-musl-g++ \
    QEMU_LD_PREFIX=/usr/local/i686-linux-muslsf \
    RUST_TEST_THREADS=1
