FROM ubuntu:24.04 as cross-base
ENV DEBIAN_FRONTEND=noninteractive

COPY common.sh lib.sh /
RUN /common.sh

COPY cmake.sh /
RUN /cmake.sh

COPY xargo.sh /
RUN /xargo.sh

FROM cross-base as build

COPY illumos.sh /
RUN /illumos.sh x86_64

COPY toolchain.cmake /opt/toolchain.cmake

ENV CROSS_TOOLCHAIN_PREFIX=x86_64-unknown-illumos-
ENV CROSS_SYSROOT=/usr/local/x86_64-unknown-illumos/sysroot
ENV PATH=$PATH:/usr/local/x86_64-unknown-illumos/bin/ \
    CARGO_TARGET_X86_64_UNKNOWN_ILLUMOS_LINKER="$CROSS_TOOLCHAIN_PREFIX"gcc \
    AR_x86_64_unknown_illumos="$CROSS_TOOLCHAIN_PREFIX"ar \
    CC_x86_64_unknown_illumos="$CROSS_TOOLCHAIN_PREFIX"gcc \
    CXX_x86_64_unknown_illumos="$CROSS_TOOLCHAIN_PREFIX"g++ \
    CMAKE_TOOLCHAIN_FILE_x86_64_unknown_illumos=/opt/toolchain.cmake \
    BINDGEN_EXTRA_CLANG_ARGS_sparcv9_sun_solaris="--sysroot=$CROSS_SYSROOT" \
    CROSS_CMAKE_SYSTEM_NAME=illumos \
    CROSS_CMAKE_SYSTEM_PROCESSOR=x86_64 \
    CROSS_CMAKE_CRT=solaris \
    CROSS_CMAKE_OBJECT_FLAGS="-ffunction-sections -fdata-sections -fPIC -m64"
