FROM ubuntu:18.04

COPY common.sh lib.sh /
RUN /common.sh

COPY cmake.sh /
RUN /cmake.sh

COPY xargo.sh /
RUN /xargo.sh

COPY qemu.sh /
RUN /qemu.sh arm

COPY musl.sh /
RUN /musl.sh \
    TARGET=arm-linux-musleabi \
    "COMMON_CONFIG += --with-arch=armv5te \
                      --with-float=soft \
                      --with-mode=arm"

# Allows qemu run dynamic linked binaries
RUN ln -sf \
    /usr/local/arm-linux-musleabi/lib/libc.so \
    /usr/local/arm-linux-musleabi/lib/ld-musl-arm.so.1
ENV QEMU_LD_PREFIX=/usr/local/arm-linux-musleabi

ENV CARGO_TARGET_ARMV5TE_UNKNOWN_LINUX_MUSLEABI_LINKER=arm-linux-musleabi-gcc \
    CARGO_TARGET_ARMV5TE_UNKNOWN_LINUX_MUSLEABI_RUNNER=qemu-arm \
    CC_armv5te_unknown_linux_musleabi=arm-linux-musleabi-gcc \
    CXX_armv5te_unknown_linux_musleabi=arm-linux-musleabi-g++ \
    RUST_TEST_THREADS=1
