#!/bin/bash

set -e

LOG=/tmp/qemu.log
LOCK=/tmp/qemu.lock

if [ -n "$CROSS_DEBUG" ]; then
    set -x
fi

# arch in the rust target
arch=$1
shift

case "$CROSS_RUNNER" in
    native)
        exec "${@}"
        ;;
    qemu-user)
        exec qemu-$arch "${@}"
        ;;
    qemu-system)
        true
        ;;
    *)
        echo "Invalid CROSS_RUNNER: $CROSS_RUNNER";
        echo "This is a bug, please report it at https://github.com/japaric/cross"
        exit 1
        ;;
esac

# 8 is the max number of cpu supported by qemu-aarch64
n=$(nproc)
n=$(( n > 8 ? 8 : n ))
memory=1G
driver9p="virtio-9p-device"
drivernet="virtio-net-device"

# select qemu parameters
case "$arch" in
    aarch64)
        opt="-machine virt -cpu cortex-a57"
        ;;
esac

(
    flock -n 200 || exit 0

    echo Booting QEMU virtual machine with $n cpus...

    QEMU_CMD="qemu-system-$arch \
        -m $memory \
        -smp $n \
        -nographic \
        -monitor none \
        -netdev user,id=net0,hostfwd=tcp::10022-:22 \
        -device $drivernet,netdev=net0 \
        -kernel /qemu/kernel \
        -initrd /qemu/initrd.gz \
        $opt \
        -fsdev local,id=fs0,path=/target,security_model=mapped \
        -device $driver9p,fsdev=fs0,mount_tag=target"

    touch $LOG
    if [ -n "$CROSS_DEBUG" ]; then
        ($QEMU_CMD 2>&1 | tee -a $LOG) &
    else
        $QEMU_CMD 2>&1 >> $LOG &
    fi

    # wait for dropbear
    tailf $LOG | grep -m1 "Not backgrounding" > /dev/null

    echo Booted in $(dbclient -K 1 -p 10022 -y -y root@localhost "cut -d' ' -f1 /proc/uptime") seconds

) 200>$LOCK

exec dbclient \
    -t \
    -p 10022 \
    -y -y \
    root@localhost \
    "${@}"
