#!/usr/bin/env bash
# A very lightweight version of linux-runner that
# doesn't support system emulation. Just useful
# to allow native or qemu-user mode emulation.

set -e

if [ -n "${CROSS_DEBUG}" ]; then
    set -x
fi

# arch in the rust target
arch="${1}"
shift

if [ "${CROSS_RUNNER}" = "" ]; then
    if [[ "${arch}" == i?86 ]] || [[ "${arch}" == x86_64 ]]; then
        CROSS_RUNNER=native
    else
        CROSS_RUNNER=qemu-user
    fi
fi

# select qemu arch
qarch="${arch}"
case "${arch}" in
    armv7)
        qarch="arm"
        ;;
    i?86)
        qarch="i386"
        ;;
    powerpc)
        qarch="ppc"
        ;;
    powerpc64)
        qarch="ppc64"
        ;;
    powerpc64le)
        if [ "${CROSS_RUNNER}" = "qemu-user" ]; then
            qarch="ppc64le"
        else
            qarch="ppc64"
        fi
        ;;
esac

case "${CROSS_RUNNER}" in
    native)
        exec "${@}"
        ;;
    qemu-user)
        exec "qemu-${qarch}" "${@}"
        ;;
    *)
        echo "Invalid runner: \"${CROSS_RUNNER}\"";
        echo "Valid runners are: native and qemu-user"
        exit 1
        ;;
esac
