name: Upload cargo install artifacts
description: Upload `cargo install` artifacts
inputs:
  target:
    description: 'Target'
    required: true

runs:
  using: composite
  steps:
    - name: Setup
      id: metadata
      run: |
        metadata="$(cargo metadata --format-version 1 --no-deps)"

        package_name="cross"
        echo "package-name=${package_name}" >> $GITHUB_OUTPUT

        out_dir="$(mktemp -d)"
        artifacts_dir="$(mktemp -d)"

        if which cygpath; then
          out_dir="$(cygpath -w "${out_dir}")"
          artifacts_dir="$(cygpath -w "${artifacts_dir}")"
        fi

        echo "out-dir=${out_dir}" >> $GITHUB_OUTPUT
        echo "artifacts-dir=${artifacts_dir}" >> $GITHUB_OUTPUT
      shell: bash
    - run: mv .git .git.bak
      shell: bash
    - name: Build with all features
      run:
        cargo install
          --locked
          --path .
          --target ${{ inputs.target }}
          --all-features
          --root ${{ steps.metadata.outputs.out-dir }}
          --bins
      shell: ${{ contains(runner.os, 'windows') && 'pwsh' || 'bash' }}
      env:
        RUSTFLAGS: "" # Make sure to unset RUSTFLAGS

    - name: Archive artifacts
      id: archive
      run: |
        set -x

        if which cygpath; then
          out_dir="$(cygpath -u "${out_dir}")"
          artifacts_dir="$(cygpath -u "${artifacts_dir}")"
        fi

        artifact_name="${package_name}-${target}"
        artifact_path="${artifacts_dir}/${artifact_name}.tar.gz"

        pushd "${out_dir}/bin"
        tar -cvzf "${artifact_path}" *
        popd

        tar -tf "${artifact_path}"
        ls -al "${artifact_path}"

        if which cygpath; then
          artifact_path="$(cygpath -w "${artifact_path}")"
        fi

        echo "name=${artifact_name}" >> $GITHUB_OUTPUT
        echo "path=${artifact_path}" >> $GITHUB_OUTPUT
      env:
        package_name: ${{ steps.metadata.outputs.package-name }}
        out_dir: ${{ steps.metadata.outputs.out-dir }}
        artifacts_dir: ${{ steps.metadata.outputs.artifacts-dir }}
        target: ${{ inputs.target }}
      shell: bash

    - name: Upload artifacts
      if: ${{ steps.archive.outputs.path }}
      uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.archive.outputs.name }}
        path: ${{ steps.archive.outputs.path }}
        if-no-files-found: error
    - run: mv .git.bak .git
      shell: bash